### PR TITLE
Made module context-aware

### LINKED ISSUE #2313: Precompiled binary bindings does not work in electron v14.0.0
Hi!
After upgrading electron to version 14.0.0 in my project, electron-builder starts to break my builds. It took me about 3 hours to figure out what is going on, so I decide to write this issue to save someone else time:

Conditions:
1. Electron 14.0.0
2. electron-builder 22.11.7
3. electron-rebuild 3.2.3
4. serialport 9.2.1
5. node 14.15.4
6. npm 7.21.0

First step, try to build up the app:
```console
$ ./node_modules/.bin/electron-builder

• electron-builder  version=22.11.7 os=5.4.0-81-generic
  • loaded configuration  file=package.json ("build" field)
  • electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • writing effective config  file=builds/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=@serialport/bindings@9.2.1 platform=linux arch=x64
  • install prebuilt binary  name=@serialport/bindings version=9.2.1 platform=linux arch=x64 napi=
  • packaging       platform=linux arch=x64 electron=14.0.0 appOutDir=builds/linux-unpacked
..... etc, all ok .....
```
Second: try to run the app (or builded unpacked one) and got the error:
```console
$  ./node_modules/.bin/electron ./dist/main.js
/home/project/node_modules/electron/dist/electron ./dist/main.js: symbol lookup error: /home/project/node_modules/@serialport/bindings/build/Release/bindings.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeEPKNS_9CFunctionE
```
Solution:
```console
$ ./node_modules/.bin/electron-rebuild -f
... compilation process ...
$ ./node_modules/.bin/electron ./dist/main.js
... all ok ...
```
If I try to `electron-builder` again, I will got the same error. I figured out that the problem is in serialport _prebuild_, exactly in `bindings-v9.2.1-electron-v89-linux-x64.tar.gz` that is being downloaded by electron-builder. I managed to successfully build my app only after following steps, to prevent _prebuild binaries_ being downloaded:
```console
$ ./node_modules/.bin/electron-rebuild -f
$ ./node_modules/.bin/electron-builder -c.npmRebuild=false
```
After downgrading Electron to 13.3.0, all works as expected: `electron-builder` downloads precompiled binaries (v89) and they work okay, nothing breaks.

So, is it okay that `bindings-v9.2.1-electron-v89` does not work with Electron v14.0.0?

### PR DESCRIPTION
**Pull request by 1pxone**
Tested it on node v14.16.0 and electron 15.3.1

I suppose that this could fix #2313 in the case of [electron/electron#18397](https://github.com/electron/electron/issues/18397) and some duplicated mentions of quite the same problems.

### CODE REVIEW

**Comment by 1pxone** [comment]
I'm absolutely a newbie at C++, but these changes helped me to run it with an updated node.js version (14, 16) and electron.

**Comment by Vahid1310** [comment]
How soon, if at all, could we expect this branch to be merged? I am currently using this module with Electron and I am having issues even with a rebuild.

**Comment by GazHank** [comment]
Haven't had chance to test the change, but this can probably be simplified since node 10 and older are no longer supported by node.js so the historic compatibility lines can probably be dropped.

**Comment by GazHank** [comment]
I'll double check, but I've managed to use two concurrent connections working in the n-api version with recent electron versions

I haven't however switched it to context aware (yet), nor have I updated the test script to cover this, so not sure if this will work without issues consistently

**Comment by chuac** [comment]
Just installed `serialport@10.0.0` thanks to [comment by @reconbot](https://github.com/serialport/node-serialport/issues/2313#issuecomment-991797836) and works great with Node v16.13.1, and Electron v16.0.0!

**Pull request closed without merging**
