### PR TITLE
Add slip decoder to parser-slip-encoder

### LINKED ISSUE #1608: Common Serial protocols: SLIP & PPP
Moving https://github.com/node-serialport/utilities/issues/10 over here 

@beriberikix asked 

> Two common protocols for communicating to serial devices are [SLIP](https://en.wikipedia.org/wiki/Serial_Line_Internet_Protocol) & [PPP](https://en.wikipedia.org/wiki/Point-to-Point_Protocol). Would make for great parsers!

They then contributed the SLIP parser! The PPP parser is still needs a champion.

### LINKED ISSUE #1609: Make a parser to pull data out from the middle of a known binary packet
We don't have a parser that makes this [very common problem](https://github.com/node-serialport/node-serialport/issues/1506#issuecomment-371834751) easy.

### PR DESCRIPTION
**Pull request by doggkruse**
Add slip decoder to parser-slip-encoder
Add option to specify slip escape codes
Add optional start and start escape

Resolves #1608

### CODE REVIEW

**Comment by doggkruse** [comment]
I assume the breaking change is the new require structure?  Is there a cleaner way to handle this?

**Comment by hrueger** [comment]
I just tried this and it works perfectly. Is there any way I can help to get this PR merged?

**Comment by hrueger** [comment]
I'd definitely help with this, but I don't have write access to @doggkruse's branch...

**Comment by doggkruse** [comment]
Thanks for getting this merged!  I'm happy to update the docs for the website but not sure how to get started?

**Pull request merged**
