### PR TITLE
add friendlyName for windows platform。

### PR DESCRIPTION
**Pull request by szyusong**

### CODE REVIEW

**Comment by caffeinatedbits** [comment]
Commit omits https://github.com/serialport/node-serialport/pull/2325/commits/737edd43edf6806607bbaf436cbb4a340ba0c6a8

**Comment by GazHank** [comment]
Would you be able to add a little info about the feature and it's purpose please?

I'm assuming this is intended to improve accesssibility or user friendlyness on Windows, but additional info would be really useful so that the [docs](https://serialport.io/docs/api-stream#serialportlist) can be maintained

**Comment by GazHank** [comment]
Hi @caffeinatedbits it doesnt seem to conflict with the `isCom = false; ` change, so isnt reverting that change or creating a problem from what I can see.  Let me know if it looks different to you.

I've popped this change into the NAPI migration version so that I check that I don't break anything when that is ready; however I would like to understand how this friendly name is intended to be used, since it creates the risk that people will code for this and create platform specific functionality (by mistake).  For the devices I have connected it doesn't seem to include any more data or look for friendly than the data in the other existing fields.

**Comment by GazHank** [comment]
@caffeinatedbits no probs, I'm having plenty of fights with the git software at the moment.  I actually had to check out the code to see if there was conflict; from what I can see the merge seems to work without issue, but am always happy to be corrected

**Comment by szyusong** [comment]
> Would you be able to add a little info about the feature and it's purpose please?
> 
> I'm assuming this is intended to improve accesssibility or user friendlyness on Windows, but additional info would be really useful so that the [docs](https://serialport.io/docs/api-stream#serialportlist) can be maintained

By the friendly name, I can easily figure out the com port which I want to use. 
[
  {
    path: 'COM2',
    manufacturer: 'ASIX',
    serialNumber: undefined,
    pnpId: 'MF\\PCI#VEN_125B&DEV_9100&SUBSYS_1000A000&REV_00\\5&382C57B4&0&0008#CHILD0000',
    locationId: undefined,
    friendlyName: 'AX99100 PCIe to High Speed Serial Port (COM2)',
    vendorId: undefined,
    productId: undefined
  },
  {
    path: 'COM3',
    manufacturer: 'ASIX',
    serialNumber: undefined,
    pnpId: 'MF\\PCI#VEN_125B&DEV_9100&SUBSYS_1000A000&REV_00\\5&1F93300A&0&0108#CHILD0000',
    locationId: undefined,
    friendlyName: 'AX99100 PCIe to High Speed Serial Port (COM3)',
    vendorId: undefined,
    productId: undefined
  },
  {
    path: 'COM4',
    manufacturer: 'Prolific',
    serialNumber: '6&36d3217e&0&3',
    pnpId: 'USB\\VID_067B&PID_2303\\6&36D3217E&0&3',
    locationId: 'Port_#0003.Hub_#0003',
    friendlyName: 'Prolific USB-to-Serial Comm Port (COM4)',
    vendorId: '067B',
    productId: '2303'
  },
  {
    path: 'COM33',
    manufacturer: 'FTDI',
    serialNumber: 'AR0JVEMU',
    pnpId: 'FTDIBUS\\VID_0403+PID_6001+AR0JVEMUA\\0000',
    locationId: undefined,
    friendlyName: 'USB Serial Port (COM33)',
    vendorId: '0403',
    productId: '6001'
  }
]

**Pull request closed without merging**
